config/routes.rb
Rails.application.routes.draw do
  root to: 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: {minimum:3, maximum:15}
  has_many :messages
  has_secure_password  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action"
      redirect_to login_path
    end 
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", 
                                  { mod_message: message_render(message) }
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   before_action :logged_in_redirect, only: [:new, :create]
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      #Good scenario
      session[:user_id] = @user.id
      flash[:success] = "You've successfully logged in"
      redirect_to root_path
    else
      #user is invalid or auth failed
      flash.now[:danger] = "There was somenthing wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You've successfully logged out"
    redirect_to login_path
  end
  
  private

  def logged_in_redirect
    if logged_in?
      flash[:warning] = "You're already logged in"
      redirect_to root_path
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<div class="d-flex flex-column align-items-center justify-content-center mb-4">
  <%= image_tag("undraw_Hang_out_re_udl4.svg", alt: "coffe", class:"chat__image")%>
  <h1 class="mt-2 fs-3">Say something</h1>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 card me-2 shadow-sm card__wrapper fs-5">
      <div class="messages">
        <div class="card-body" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="card-footer bg-white">
        <%= form_for(@message, html: {role: "form"}, url: message_path, remote: true) do |f|%>
          <div class="d-flex">
            <%= f.text_field :body, placeholder: "Text your message...", class:"form-control me-2", autocomplete: 'off'%>
            <%= f.button '<i class="fas fa-paper-plane"></i>'.html_safe, class:"btn btn-secondary"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 card shadow-sm card__wrapper">
      <div class="card-body">
        <div class="btn-group-vertical card__menu rounded">
          <a href="#" class="btn card__menu-btn">Home</a>
          <a href="#" class="btn card__menu-btn">Messages</a>
          <a href="#" class="btn card__menu-btn">Friends</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content|%>
  <div class="alert alert-<%=message_type%> alert-dismissible fade show mt-2" role="alert">
    <%= message_content %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'MessageApp!', root_path, class:"navbar-brand"%>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Messages</a>
        </li>
      </ul>
      <div class="dropdown me-2">
        <a
          class="btn btn-secondary dropdown-toggle"
          href="#"
          role="button"
          id="dropdownMenuLink"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Account
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <% if logged_in? %>
          <li>
            <%= link_to 'Log out', logout_path, method: :delete, class:"dropdown-item"%>
          </li>
          <% else %>
          <li><%= link_to 'Log In', login_path, class:"dropdown-item"%></li>
        <% end %>
        </ul>
      </div>
      <% if !logged_in? %>
        <%= link_to 'Log In', login_path, class:"btn btn-primary mrt"%>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<p class="card-text">
  <em class="fw-bold">
    <%= message.user.username%>:
  </em>
  <%= message.body %>
</p>